# Generated by Django 4.2.7 on 2024-06-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_remove_survey_profile_survey_advanced_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="constraints",
        ),
    ]
