# Generated by Django 4.2.7 on 2024-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tooltip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("markdown_file", models.FilePathField(path="../../../docs/tooltips")),
            ],
        ),
    ]
