# Generated by Django 4.2.7 on 2024-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_documentation_delete_tooltip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentation",
            name="markdown_file",
            field=models.FilePathField(path="../../docs"),
        ),
    ]
