# Generated by Django 4.2.7 on 2024-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_documentation_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentation",
            name="markdown_file",
            field=models.FilePathField(
                path="/Users/akhat/Projects/projointdesigntool/backend/../docs"
            ),
        ),
    ]
